version: '19.03.0'
services:
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    environment:
    - SECRET_KEY=django-insecure-6!kl21i5!p*(n6a@s82_781(u_axzh-auce3-0xt(k(#z0@btu
    - DEBUG=1
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: